name: Upload Artifact to Release

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Get current timestamp
      id: timestamp
      run: echo "current=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.11'
    
    - name: Install dependencies
      run: |
        julia --project=artifacts_scripts -e 'using Pkg; Pkg.instantiate()'
    
    - name: Execute Julia script
      id: julia_script
      run: | 
        cd eop_artifacts
        echo "Executing script: eop_artifacts/create_eop_artifact.jl"
        julia --project=. -e "include(\"create_eop_artifact.jl\")"
        
        # Check if assets directory exists and find generated files
        if [ -d "assets" ]; then
          echo "Assets directory found"
          ls -la assets/
          
          # Find the most recently created file in assets directory
          ASSET_FILE=$(ls -t assets/ | head -n 1)
          ASSET_PATH="assets/$ASSET_FILE"
          
          echo "asset_file=$ASSET_FILE" >> $GITHUB_OUTPUT
          echo "asset_path=$ASSET_PATH" >> $GITHUB_OUTPUT
          
          echo "Generated asset: $ASSET_FILE"
          echo "Asset path: $ASSET_PATH"
        else
          echo "No assets directory found"
          exit 1
        fi
    
    - name: Verify asset exists
      run: |
        if [ ! -f "${{ steps.julia_script.outputs.asset_path }}" ]; then
          echo "Asset file not found: ${{ steps.julia_script.outputs.asset_path }}"
          exit 1
        fi
        
        echo "Asset file verified: ${{ steps.julia_script.outputs.asset_path }}"
        echo "File size: $(du -h "${{ steps.julia_script.outputs.asset_path }}" | cut -f1)"
    
    - name: Upload to artifact_releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: artifacts_releases
        name: artifacts_releases
        files: ${{ steps.julia_script.outputs.asset_path }}
        append_body: true
        make_latest: false
        body: |
          Uploaded artifact: `${{ steps.julia_script.outputs.asset_file }}`
          - Script executed: [`${{ github.event.inputs.script }}`](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/eop_artifacts/create_eop_artifact.jl)
          - Created at: ${{ steps.timestamp.outputs.current }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check for Artifacts.toml changes
      id: check_changes
      run: |
        if git diff --quiet HEAD -- Artifacts.toml; then
          echo "No changes to Artifacts.toml"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in Artifacts.toml"
          echo "has_changes=true" >> $GITHUB_OUTPUT
          git diff HEAD -- Artifacts.toml
        fi
    
    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update Artifacts.toml after generating ${{ steps.julia_script.outputs.asset_file }}"
        title: "Update Artifacts.toml - ${{ steps.julia_script.outputs.asset_file }}"
        body: |
          This PR updates the Artifacts.toml file after generating and uploading the artifact: `${{ steps.julia_script.outputs.asset_file }}`
          
          **Details:**
          - Script executed: [`create_eop_artifact.jl`](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/eop_artifacts/create_eop_artifact.jl)
          - Artifact uploaded: `${{ steps.julia_script.outputs.asset_file }}`
          - Generated at: ${{ steps.timestamp.outputs.current }}
          
          This PR was automatically created by the artifact generation workflow.
        branch: update-artifacts-toml-${{ github.run_number }}
        base: ${{ github.ref_name }}
        delete-branch: true
        draft: false 